platform :ios, '10.0'

target 'example' do
	rn_path = '../node_modules/react-native'

	pod 'React', :path => "#{rn_path}"
	pod 'React-ART', :path => "#{rn_path}/Libraries/ART"
	pod 'React-Core', :path => "#{rn_path}/React"
	pod 'React-DevSupport', :path => "#{rn_path}/React"
	pod 'React-RCTActionSheet', :path => "#{rn_path}/Libraries/ActionSheetIOS"
	pod 'React-RCTAnimation', :path => "#{rn_path}/Libraries/NativeAnimation"
	pod 'React-RCTBlob', :path => "#{rn_path}/Libraries/Blob"
	pod 'React-RCTImage', :path => "#{rn_path}/Libraries/Image"
	pod 'React-RCTLinking', :path => "#{rn_path}/Libraries/LinkingIOS"
	pod 'React-RCTNetwork', :path => "#{rn_path}/Libraries/Network"
	pod 'React-RCTSettings', :path => "#{rn_path}/Libraries/Settings"
	pod 'React-RCTText', :path => "#{rn_path}/Libraries/Text"
	pod 'React-RCTVibration', :path => "#{rn_path}/Libraries/Vibration"
	pod 'React-RCTWebSocket', :path => "#{rn_path}/Libraries/WebSocket"

	pod 'React-cxxreact', :path => "#{rn_path}/ReactCommon/cxxreact"
	pod 'React-jsi', :path => "#{rn_path}/ReactCommon/jsi"
	pod 'React-jsiexecutor', :path => "#{rn_path}/ReactCommon/jsiexecutor"
	pod 'React-jsinspector', :path => "#{rn_path}/ReactCommon/jsinspector"
	pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

	# Third party deps podspec link
	pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
	pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
	pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"

	pod 'react-native-cronet', :path => '../../react-native-cronet.podspec'

	target 'exampleTests' do
		inherit! :search_paths
	end
end
